Feature: AverageTrueRange
enzoampil/fastquant pull request #282
Opened 2020-10-28 15:39 UTC by sgoley

Motivation of PR: 
https://github.com/enzoampil/fastquant/issues/275

Description of intended feature:
https://www.investopedia.com/terms/a/atr.asp

New Strategy added:
ATRStrategy

Strategy Arguments: 
- Period
- Multiplier

2020-10-29 20:10 UTC, jbdelmundo commented
Hi @sgoley 
You also need to import your strategy in `fastquant/strategies/__init__.py` to fix the import error on tests

2020-11-01 00:56 UTC, enzoampil requested changes
Thanks for this @sgoley , and for providing an issue as context, and an investopedia article to elaborate to strategy :smile:

I'm generally okay, but let's start with fixing the build error due to the wrong indexing. I'll see if it's quick to resolve. For now, kindly note the lines I'm referring to in the comments :smile:

Also, you'll see that I made some corrections to the indexing, mainly around getting the "last" data point using `-1` instead of `1`. Also, you'll see that created a new `set_trailing_stop` method that ensures that the indexing only runs during the actual strategy run (called during `buy_signal` and `sell_signal`.

2020-11-01 00:56 UTC, enzoampil commented on python/fastquant/strategies/atr.py
> +        self.lastdataclose = self.datas[1].close
@sgoley I think you may have meant `self.datas[-1]` if you were intending to utilize the previous close?

2020-11-01 00:56 UTC, enzoampil commented on python/fastquant/strategies/atr.py
> +        self.lastdataclose = self.datas[1].close
```suggestion
        self.lastdataclose = self.datas[-1].close
```

2020-11-01 00:56 UTC, enzoampil commented on python/fastquant/strategies/atr.py
> +        self.lastdataopen = self.datas[1].open
```suggestion
        self.lastdataopen = self.datas[-1].open
```

2020-11-01 00:56 UTC, enzoampil commented on python/fastquant/strategies/atr.py
> +        self.lastdataopen = self.datas[1].open
Same comments as dataclose

2020-11-03 18:21 UTC, sgoley commented
I'm trying to see how I can build this and test via a local env before merging. 
Is the best way to do that something like the standard `python3 setup.py sdist bdist_wheel` and then install through pip locally from the wheel?
Thanks.

2020-11-04 00:32 UTC, enzoampil commented
@sgoley Yes, that's one way to do it.

Might be faster to just navigate to run your script / jupyter notebook from `fastquant/python`.

You should be able to import normally from here.

Guideline is found in [CONTRIBUTING.md](https://github.com/enzoampil/fastquant/blob/master/CONTRIBUTING.md#get-started)

2020-11-10 00:50 UTC, enzoampil commented
@sgoley Any update with this? Happy to help out however I can to get this merged :smile:

2021-04-01 23:25 UTC, closed without merging